In [1]:
import numpy as np

In [2]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [7]:
result = np.fromfunction(lambda i, j: i * j, arr.shape, dtype=int)
print(result)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]


In [2]:
import wave

In [9]:
# Open the WAV file
with wave.open('do_v3.wav', "rb") as do:
    nchannels = do.getnchannels()
    sample_wid = do.getsampwidth()
    framerate = do.getframerate()
    nframes = do.getnframes()

    # Define the start and end positions (in milliseconds)
    start_time_ms = 0  # Start at 2.5 seconds (2500 ms)
    end_time_ms = 1100    # End at 5.2 seconds (5200 ms)

    # Convert time in milliseconds to frame positions
    start_frame = int((start_time_ms / 1000) * framerate)
    end_frame = int((end_time_ms / 1000) * framerate)

    # Set the position to the start frame
    do.setpos(start_frame)

    # Read frames from start to end
    frames = do.readframes(end_frame - start_frame)

# Save the extracted frames to a new WAV file
with wave.open('do_v3_cut.wav', "wb") as output:
    output.setnchannels(nchannels)
    output.setsampwidth(sample_wid)
    output.setframerate(framerate)
    output.writeframes(frames)